### ISSUE TITLE
No video files were found in the selected folder.

### ISSUE THREAD

**Issue by ErikTMA** [docker-hotio/docker-sonarr#13]
Hi,

I am getting the error "No video files were found in the selected folder" with some of the torrents being downloaded, not all.

In the log file sonarr.txt, I have these lines: 20-12-2 06:37:07.5|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /storage/galaxy/downloads/****omitted****[eztv.re].mp4[eztv]

But if I run this command inside the sonarr container, it finds the file fine: ls -l /storage/galaxy/downloads/****omitted****[eztv.re].mp4
I am unaware if it actually tries looking for the [eztv] at the end or if it is just the log saying which indexer it found it through?

Here is the relevant data from my docker-compose

```
---
version: "2.1"
services:
  sonarr:
    image: hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK=002
      - ARGS=""
      - DEBUG="no"
    volumes:
      - /home/etma/private-server/containers/sonarr/config:/config
      - /storage/galaxy:/storage/galaxy
      - /storage/world:/storage/world
      - /home/etma/private-server/containers/ssl/config/etc/letsencrypt:/etc/letsencrypt
    ports:
      - 8989:8989
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK_SET=002
      - WEBUI_PORT=8080
    volumes:
      - /home/etma/private-server/containers/qbittorrent/config:/config
      - /storage/galaxy:/storage/galaxy
      - /storage/world:/storage/world
      - /home/etma/private-server/containers/ssl/config/etc/letsencrypt:/etc/letsencrypt
    ports:
      - 39862:39862
      - 39862:39862/udp
      - 8080:8080
    restart: always
```

I have tried changing the permissions to 0777 without any luck either.

Sonarr also reports: "Cannot install update because startup folder '/app' is not writable by the user 'hotio'." - not sure if this is relevant to this issue though.

The etma user on the host is uid 1000 as well

**Comment by hotio** [comment]
I believe that is an issue caused by the latest version of qbittorrent, you might need to rollback to an older version, lots of talk has been made on the sonarr/radarr discord servers...

The `Cannot install update because startup folder '/app' is not writable by the user 'hotio'.`is on purpose...I make sure that the user running sonarr cannot overwrite the installation files to block updating sonarr from within the app. Sonarr v3 has methods in place to solve this more cleanly....Just disable the auto update feature and update the container as in intended by docker guidelines.

**Comment by ErikTMA** [comment]
Just a followup.

Thanks for your reply. I updated qbittorrent to the newer version today along with updating to your hotio/sonarr:nightly build and it seems the problem went away :)
